# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "centos/7"
  #config.vm.hostname = "centosbase"
  config.vm.box_check_update = false
  config.vm.network "private_network", type: "dhcp"

  config.vm.provision :shell, path: "bootstrap.sh"
end
